apiVersion: v2
name: nextdns-operator
description: A Kubernetes operator for managing NextDNS profiles declaratively
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0-0"
keywords:
  - nextdns
  - dns
  - operator
  - kubernetes
home: https://github.com/jacaudi/nextdns-operator
sources:
  - https://github.com/jacaudi/nextdns-operator
maintainers:
  - name: jacaudi
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.0.1
